### ISSUE TITLE
Error when rendering anonymus component

### ISSUE THREAD

**Issue by ackzell** [Akryum/meteor-vue-example#1]
Hello @Akryum, this is very exciting. Having Vue as a front end for Meteor sounds like a great combo.

I have been trying to run the examples for Vue 2.x but I unfortunately can not. I even cloned the repos, `meteor npm install`ed the dependencies, but to no avail.

This is the recurring issue I am having:

![image](https://cloud.githubusercontent.com/assets/601266/21202807/82262dec-c215-11e6-8ea8-9f9067f1b2a4.png)

I'm not super familiar with Vue.js yet so, I can't really tackle the issue. Would you mind sharing any input you have on this?

**Comment by ackzell** [comment]
I downgraded Vue to `2.0.0-rc.8` and it works now. 

I can't really tell what is breaking, but I'll try to dig deeper into this.

**Comment by ackzell** [comment]
This might be related
https://github.com/Akryum/meteor-vue-component/issues/92

**Comment by Akryum** [comment]
Yes, closing in favor of https://github.com/Akryum/meteor-vue-component/issues/92
