### ISSUE TITLE
Update to Vue 2.0?

### ISSUE THREAD

**Issue by EMHmark7** [Akryum/meteor-vue-example#2]
Is there an update for Vue 2.0? What is need to update it with Vue 2.0?

If one wants to rebuild this project manually, is there a liste of steps?

Thanks,
Marc

**Comment by Akryum** [comment]
Hi! Yes, there is a [vue 2 version](https://github.com/Akryum/meteor-vue2-example). [Here](https://github.com/Akryum/meteor-vue-example#steps-to-reproduce) are some steps to create this example, but don't forget to install vue 2.0 with `npm install --save vue@^2.1.6`.

**Comment by MarcTe** [comment]
Is it 2 AM for you?!

**Comment by Akryum** [comment]
Almost! 🐈

**Comment by MarcTe** [comment]
Hope it was for good coding! or...

**Comment by Akryum** [comment]
Sure! 😸

**Comment by EMHmark7** [comment]
Do you see a problem if I just follow the vue 2 version install or I need to uninstall something?

**Comment by Akryum** [comment]
Well, installing the new vue version should be alright.

**Comment by MarcTe** [comment]
Merci!
