### ISSUE TITLE
Installing vue in Meteor

### ISSUE THREAD

**Issue by EMHmark7** [Akryum/meteor-vue-example#3]
Following up on previous issue,

I got some install problems, described here: [vue forum](https://forum.vuejs.org/t/problem-installing-vue-2-on-windows-8-1/4224)

In main.js, I have:
```
import {Meteor} from 'meteor/meteor';
import {Vue} from 'meteor/akryum:vue';
```

1) I suppose, Vue is installed through akryum:vue.

2) Do you know if it makes a difference at what dir I am when I install Vue?
What should I do so, when I declare these 2 lines in any project, Vue will install?

Thanks,
Marc

**Comment by Akryum** [comment]
Use `import Vue from 'vue'` instead.
