### ISSUE TITLE
It does not work with Vue 2.0

### ISSUE THREAD

**Issue by mitar** [Akryum/meteor-vue-example#4]
Upgrading to Vue 2.0 does not work:

```
meteor npm install --save vue@^2.0.3
```

Error:

```
[Vue warn]: Failed to mount component: template or render function not defined.
```

**Comment by mitar** [comment]
Ah, I see: https://github.com/Akryum/meteor-vue2-example

**Comment by Akryum** [comment]
Vue is not bundled with the template compiler, so you can't use the `template` or `replace:false` options. This will not work:

```html
<body>
  <app></app>
</body>
```

```javascript
import Vue from 'vue';

Meteor.startup(() => {
  new Vue({
    el: 'body',
    replace: false
  });
});
```
But the following will work:

```html
<body>
</body>
```

```javascript
import Vue from 'vue';

Meteor.startup(() => {
  new Vue({
    el: 'body',
    render: h => h('app')
  });
});
```

**Comment by mitar** [comment]
Yes, I tried also `template` and I got a helpful message. But it is sad that I did not get such a message also for `el` approach with `replace`. I am not even sure if `replace` even exists in 2.0.

I saw how to do it in 2.0 example.

But would not your example above *replace* body? Currently I have:

```js
Meteor.startup(() => {
  new Vue({
    render: (createElement) => {
      return createElement(Vue.component('app'));
    }
  }).$mount('app');
});
```

And:

```html
<body>
  <app></app>
</body>
```

**Comment by Akryum** [comment]
It will effectively replace the content of body, so you can remove `<app></app>`.

**Comment by mitar** [comment]
The content of body, or the body itself? It seems it replaces the tag, not injects into it (`<app></app>`) is removed.

**Comment by Akryum** [comment]
The body itself. Generally I put a `<div id="app">` and `el:'#app'`.
